activestack:
  image: anazakellc/nodegateway:0.0.1
  ports:
   - "8080:8080"
  volumes:
   - ./node-gateway:/code
  links:
   - redis
   - mysql
   - rabbitmq
taskmanager:
  image: anazakellc/taskmanager:0.0.1
  volumes:
   - ./taskmanager:/code
  links:
   - redis
   - mysql
   - rabbitmq
   - activestack
redis:
  image: redis:2.8
  ports:
   - "6379:6379"
  volumes:
    - /data/redis:/data
mysql:
  image: mysql:5.6
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: gCvp8nN2
  volumes:
    - /data/mysql:/var/lib/mysql
rabbitmq:
  image: rabbitmq:3.4 
  ports:
   - "5672:5672"

