gateway:
  build: gateway
  ports:
   - "8080:8080"
   - "8081:8081"
  volumes:
   - gateway:/code
  links:
   - redis
   - mysql
   - rabbitmq
syncengine:
  build: syncengine 
  volumes:
   - syncengine:/code
  links:
   - redis
   - mysql
   - rabbitmq
   - gateway
redis:
  image: redis:2.8
  ports:
   - "6379:6379"
  volumes:
    - /data/redis:/data
mysql:
  image: mysql:5.6
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: gCvp8nN2
rabbitmq:
  image: rabbitmq:3.4 
  ports:
   - "5672:5672"

