!com.pulse.dataprovider.SqlConnectionFactory
name: default
driverClassName: oracle.jdbc.OracleDriver
jdbcUrl: jdbc:oracle:thin:@//cvgoedw1.dcd.convergys.com:1521/edwrt.world
username: PULSEUSER
password: V2PULSEUSER
---
!com.pulse.dataprovider.SqlConnectionFactory
name: estart
driverClassName: oracle.jdbc.OracleDriver
jdbcUrl: jdbc:oracle:thin:@//odcpdb01.dcd.convergys.com:1521/cybtim.cmg.convergys.com
username: pulse
password: pulse