# CMS Test DB
driverClassName: oracle.jdbc.OracleDriver
jdbcUrl: jdbc:oracle:thin:@//cvgoedw1.dcd.convergys.com:1521/dasht
username: PULSEUSER
password: V2PULSEUSER
tableNames:
 - mob_update_table
weight: 10
storedProcedureName: PULSEUSER.UPDATE_TABLE_LOCK
storedProcedureDefinition: create or replace PROCEDURE UPDATE_TABLE_LOCK (new_lock_id IN NUMBER DEFAULT 123456,lock_date VARCHAR,result_id OUT NUMBER) AS new_id NUMBER(3); BEGIN update mob_update_table u set u.lock_ID=new_lock_id, u.lock_Date=current_timestamp where (lock_id is null or lock_date < to_date(lock_date,'YYYY-MM-dd HH:mi:ss')) and ROWNUM <= 1; commit; result_id:=-1; SELECT u.ID INTO result_id FROM mob_update_table u WHERE u.lock_id=new_lock_id AND rownum<=1; EXCEPTION WHEN OTHERS THEN new_id:=-1; ROLLBACK; END UPDATE_TABLE_LOCK;
#updateStatementSql: update :tableName set lock_id=:lockId, lock_date=CURRENT_TIMESTAMP where (lock_id is null or lock_date < to_date(':expireThreshold','YYYY-MM-dd HH:mi:ss')) and ROWNUM <= 1
